### ISSUE TITLE
getCumulativePosition messed up by http.POST

### ISSUE THREAD

**Issue by ivukotic** [RobTillaart/AS5600#62] opened 2024-03-17 15:07 UTC
Hi,
not sure if this is a bug or a feature. I am reading getCumulativePosition from 8 sensors every 100 ms. 
After some time, I upload the data using http.POST (ESP Async Web Server). If sensor moved during the upload, getCumulativePosition skips (didn't notice the movement).
Best,
I

**Comment by RobTillaart** [comment] 2024-03-17 15:30
Thanks for the issue, 

The context:
```cpp
int32_t AS5600::getCumulativePosition()
{
  int16_t value = readReg2(AS5600_ANGLE) & 0x0FFF;     <<<<<<<<<<< (1)

  //  whole rotation CW?
  //  less than half a circle
  if ((_lastPosition > 2048) && ( value < (_lastPosition - 2048)))
  {
    _position = _position + 4096 - _lastPosition + value;
  }
  //  whole rotation CCW?
  //  less than half a circle
  else if ((value > 2048) && ( _lastPosition < (value - 2048)))
  {
    _position = _position - 4096 - _lastPosition + value;
  }
  else _position = _position - _lastPosition + value;   <<<<<<<<<<< (3)
  _lastPosition = value;

  return _position;
}

....

uint16_t AS5600::readReg2(uint8_t reg)
{
  _error = AS5600_OK;
  _wire->beginTransmission(_address);
  _wire->write(reg);
  if (_wire->endTransmission() != 0)
  {
    _error = AS5600_ERROR_I2C_READ_2;
    return 0;      <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< (2)
  }
  uint8_t n = _wire->requestFrom(_address, (uint8_t)2);
  if (n != 2)
  {
    _error = AS5600_ERROR_I2C_READ_3;
    return 0;  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< (2)
  }
  uint16_t _data = _wire->read();
  _data <<= 8;
  _data += _wire->read();
  return _data;
}

```

**GetCumulativePosition()** does not check if  (1) the **readReg2()** call works or not. 
The ESP webserver may disrupt this I2C read (2) which returns 0 and does not see any movement.
If this happens a few times in a row, **GetCumulativePosition()** will read zero movement.
Then it will execute line (3)  with both _lastPosition and value zero ==> no movement.

No, this is not a feature, so it classifies as a bug ==> need to be fixed.

**Comment by RobTillaart** [comment] 2024-03-17 15:38
**GetCumulativePosition()** should check _error to catch the incorrect read.
The best it can do is 
- not update _lastPosition so it can be used when there is a correct read, assuming within half rotation.
- return _position.
- not clear the error state so you can check **lastError()** if **getCumulativePosition()** is updated or not, 
and optionally call it again.

in code this would add one line in the library.

```cpp
int32_t AS5600::getCumulativePosition()
{
  int16_t value = readReg2(AS5600_ANGLE) & 0x0FFF;
  if (_error != AS5600_OK) return _position;

  //  whole rotation CW?
  //  less than half a circle
  if ((_lastPosition > 2048) && ( value < (_lastPosition - 2048)))
  {
    _position = _position + 4096 - _lastPosition + value;
  }
  //  whole rotation CCW?
  //  less than half a circle
  else if ((value > 2048) && ( _lastPosition < (value - 2048)))
  {
    _position = _position - 4096 - _lastPosition + value;
  }
  else _position = _position - _lastPosition + value;   <<<<<<<<<<< (3)
  _lastPosition = value;

  return _position;
}
```

**Comment by RobTillaart** [comment] 2024-03-17 16:54
Can you verify if the proposed patch works for you?

**Comment by ivukotic** [comment] 2024-03-17 19:56
Hi,

thanks for the very quick reply. I tried your fix but it did not help. 
`_error != AS5600_OK`  is never true.

Best,
I

**Comment by RobTillaart** [comment] 2024-03-17 20:04
Mmm, 
Need to investigate if another scenario exists that can explain what happened. Will be difficult.

Can you add a check for lastError() after your calls to getCumulativePosition() to see if it fails and if so what the error code is.

**Comment by ivukotic** [comment] 2024-03-17 20:31
I added lastError call . It always return 0.
I

**Comment by RobTillaart** [comment] 2024-03-18 09:00
> I added lastError call . It always return 0.

So that excludes the scenario above. To be continued.

**Comment by RobTillaart** [comment] 2024-03-20 12:55
FYI,
not found a cause yet as it is unclear why there is not rotation seen.

Can you add a print statement in the function to see what values are read from the sensor?

```cpp
int32_t AS5600::getCumulativePosition()
{
  int16_t value = readReg2(AS5600_ANGLE) & 0x0FFF;
  Serial.println(value);
```

**Comment by ivukotic** [comment] 2024-03-30 03:55
Hi,
it is really hard to see from a printout as I have 8 sensors read every 100ms. 
but my application takes always covers the same angular range and I can plot min and max values of the range. Normally range is ~5900 counts. If I plot the values, I see that range increases:
![image](https://github.com/RobTillaart/AS5600/assets/1736984/d41d6fcf-90fa-40a4-8ce6-751d4288ce18)

**Comment by RobTillaart** [comment] 2024-03-30 08:17
Still can't explain the behaviour.

Could it be that the wifi signal distorts the sensor?

Have you tried to make a plot of raw reads?
That might help to see if it is a sensor problem .

**Comment by ivukotic** [comment] 2024-03-30 15:34
it is not wifi signal... When I turn off http post part and leave only part that sends data as events to the website (again via wifi), everything is fine. Here actual counts:
![image](https://github.com/RobTillaart/AS5600/assets/1736984/956eea4f-0052-4219-a571-32acfc68dfc3)
you may notice that normally I sleep 100ms after each read out. But then suddenly at 31:20.333 delay is 900 ms and count jumped outside normal range...

**Comment by RobTillaart** [comment] 2024-03-31 12:18
> it is not wifi signal... When I turn off http post part and leave only part that sends data as events to the website (again via wifi), everything is fine.

Too fast a conclusion imho,
these events probably have different data size, use other timing, which might be less interfering.

Q1: What data do you send over the HTTP POST?
Q2: How long does the POST take? 

So far I do see problems in the library (except for the read error not handled before).

Maybe it is time to post your question on the Arduino forum or so

**Comment by RobTillaart** [comment] 2024-03-31 15:09
Have you read #28 ?
might be same problem.

**Comment by RobTillaart** [comment] 2024-03-31 15:28
Created a develop branch + PR for the patch for **getCumulativePosition()** + some pending things.

**Comment by ivukotic** [comment] 2024-04-01 15:26
I will try suggestions from #28 and let you know what happens.

**Comment by RobTillaart** [comment] 2024-04-11 07:55
> I will try suggestions from #28 and let you know what happens.

Any new insights?

**Comment by RobTillaart** [comment] 2024-04-16 19:28
@ivukotic 
As there is no feedback, I assume the problem is solved so I close this issue.
Feel free to reopen it if needed.

**Closed by RobTillaart** 2024-04-16 19:28 UTC
Labels: bug

**Comment by ivukotic** [comment] 2024-04-20 21:02
Hi Rob,
sorry for not commenting earlier. At the end I circumvented the issue by not posting from ESP32 but from the client side (client gets the same data via SSE).
best,
i

**Comment by RobTillaart** [comment] 2024-04-21 01:00
Good to hear you found a way to work around / solve the issue. Still I can not explain why / what happened that caused the issue in the first place.

Thanks
